defmodule KubeMQ.EventStore do
  @moduledoc """
  Persistent event message for the KubeMQ Events Store pattern.

  Unlike regular events, store events are persisted and can be replayed from
  various start positions. The `store` field is always `true` internally.

  ## Fields

    * `id` (`String.t() | nil`) — Unique event identifier. Auto-generated by the server if nil.
    * `channel` (`String.t()`) — Target channel name. Required for sending.
    * `metadata` (`String.t() | nil`) — Optional metadata string.
    * `body` (`binary() | nil`) — Message payload.
    * `client_id` (`String.t() | nil`) — Sender identifier. Set automatically by `KubeMQ.Client`.
    * `tags` (`%{String.t() => String.t()}`) — Key-value tags for filtering. Default: `%{}`.

  ## Usage

      event = KubeMQ.EventStore.new(channel: "audit-log", body: "user login")
      {:ok, result} = KubeMQ.Client.send_event_store(client, event)
  """

  @type t :: %__MODULE__{
          id: String.t() | nil,
          channel: String.t(),
          metadata: String.t() | nil,
          body: binary() | nil,
          client_id: String.t() | nil,
          tags: %{String.t() => String.t()}
        }

  defstruct [:id, :channel, :metadata, :body, :client_id, tags: %{}]

  @doc """
  Create a new EventStore struct from keyword options.

  ## Options

    * `:id` — Event ID string (auto-generated if nil)
    * `:channel` — Target channel name (required for sending)
    * `:metadata` — Metadata string
    * `:body` — Message body (binary)
    * `:client_id` — Client identifier (set automatically by `KubeMQ.Client`)
    * `:tags` — Key-value tags map (default: `%{}`)

  ## Examples

      iex> event = KubeMQ.EventStore.new(channel: "audit-log", body: "user login")
      iex> event.channel
      "audit-log"
      iex> event.body
      "user login"
  """
  @spec new(keyword()) :: t()
  def new(opts \\ []) do
    %__MODULE__{
      id: Keyword.get(opts, :id),
      channel: Keyword.get(opts, :channel),
      metadata: Keyword.get(opts, :metadata),
      body: Keyword.get(opts, :body),
      client_id: Keyword.get(opts, :client_id),
      tags: Keyword.get(opts, :tags, %{})
    }
  end
end
